version: '3'
services:
  nginx:
    build: src/nginx/.
    container_name: nginx
    ports: 
      - 8080:80
    volumes:
      - ./web:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
  wordpress:
    build: src/wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
  mariadb:
    build: src/mariadb/.
    container_name: mariadb
    networks:
      - inception
networks:
  inception:
