version: "3"
services:
  nginx:
    build: src/nginx/.
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
  wordpress:
    build: src/wordpress/.
    container_name: wp-php
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
  mariadb:
    build: src/mariadb/.
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
networks:
  inception:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/emgarcia/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/emgarcia/data/mariadb
